In [37]:
import pandas as pd
df = pd.read_excel(r'C:\Users\DHIRAJ CHAUDHARY\Desktop\DIGIPERFORM\EXCEL\SUPER SAMPLE DATA.xlsx')
print(df)

     Unnamed: 0        ORDER ID           Unnamed: 2           Unnamed: 3  \
0             1  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
1             2  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
2             3  CA-2016-138688  2016-12-06 00:00:00            6/16/2016
3             4  US-2015-108966  2015-11-10 00:00:00           10/18/2015
4             5  US-2015-108966  2015-11-10 00:00:00           10/18/2015
..          ...             ...                  ...                  ...
149         150  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
150         151  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
151         152  CA-2016-158834            3/13/2016            3/16/2016
152         153  CA-2016-158834            3/13/2016            3/16/2016
153         154  CA-2015-124919            5/31/2015  2015-02-06 00:00:00

         Unnamed: 4 customer ID      customer name     segement  \
0      Second Class    CG-12520        Claire Gute     Consumer
1      Second Class    CG-12520        Claire Gute     Consumer
2      Second Class    DV-13045    Darrin Van Huff    Corporate
3    Standard Class    SO-20335     Sean O'Donnell     Consumer
4    Standard Class    SO-20335     Sean O'Donnell     Consumer
..              ...         ...                ...          ...
149  Standard Class    JE-16165     Justin Ellison    Corporate
150  Standard Class    JE-16165     Justin Ellison    Corporate
151     First Class    TW-21025  Tamara Willingham  Home Office
152     First Class    TW-21025  Tamara Willingham  Home Office
153     First Class    SP-20650   Stephanie Phelps    Corporate

           country             city  ... postal code    Rgion  \
0    United States        Henderson  ...       42420    South
1    United States        Henderson  ...       42420    South
2    United States      Los Angeles  ...       90036     West
3    United States  Fort Lauderdale  ...       33311    South
4    United States  Fort Lauderdale  ...       33311    South
..             ...              ...  ...         ...      ...
149  United States         Franklin  ...       53132  Central
150  United States         Franklin  ...       53132  Central
151  United States       Scottsdale  ...       85254     West
152  United States       Scottsdale  ...       85254     West
153  United States         San Jose  ...       95123     West

          product ID         category sub-category  \
0    FUR-BO-10001798        Furniture    Bookcases
1    FUR-CH-10000454        Furniture       Chairs
2    OFF-LA-10000240  Office Supplies       Labels
3    FUR-TA-10000577        Furniture       Tables
4    OFF-ST-10000760  Office Supplies      Storage
..               ...              ...          ...
149  FUR-CH-10000454        Furniture       Chairs
150  OFF-BI-10002735  Office Supplies      Binders
151  OFF-AP-10000326  Office Supplies   Appliances
152  TEC-PH-10001254       Technology       Phones
153  OFF-PA-10001950  Office Supplies        Paper

                                          product name      sales  \
0                    Bush Somerset Collection Bookcase   261.9600
1    Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400
2    Self-Adhesive Address Labels for Typewriters b...    14.6200
3        Bretford CR4500 Series Slim Rectangular Table   957.5775
4                       Eldon Fold 'N Roll Cart System    22.3680
..                                                 ...        ...
149  Hon Deluxe Fabric Upholstered Stacking Chairs,...  1951.8400
150                   GBC Prestige Therm-A-Bind Covers   171.5500
151  Belkin 7 Outlet SurgeMaster Surge Protector wi...   157.9200
152           Jabra BIZ 2300 Duo QD Duo CordedÂ Headset   203.1840
153  Southworth 25% Cotton Antique Laid Paper & Env...    58.3800

         Unnamed: 18 Unnamed: 19     #name
0    FUR-BO-10001798        0.00   41.9136
1    FUR-CH-10000454        0.00  219.5820
2    OFF-LA-10000240        0.00    6.8714
3    FUR-TA-10000577        0.45 -383.0310
4    OFF-ST-10000760        0.20    2.5164
..               ...         ...       ...
149  FUR-CH-10000454        0.00  585.5520
150  OFF-BI-10002735        0.00   80.6285
151  OFF-AP-10000326        0.20   17.7660
152  TEC-PH-10001254        0.20   15.2388
153  OFF-PA-10001950        0.00   26.2710

[154 rows x 21 columns]

In [39]:
df.iloc[:10,3:6]

            Unnamed: 3      Unnamed: 4 customer ID
0  2016-11-11 00:00:00    Second Class    CG-12520
1  2016-11-11 00:00:00    Second Class    CG-12520
2            6/16/2016    Second Class    DV-13045
3           10/18/2015  Standard Class    SO-20335
4           10/18/2015  Standard Class    SO-20335
5            6/14/2014  Standard Class    BH-11710
6            6/14/2014  Standard Class    BH-11710
7            6/14/2014  Standard Class    BH-11710
8            6/14/2014  Standard Class    BH-11710
9            6/14/2014  Standard Class    BH-11710

In [41]:
df.rename(columns={'product ID': 'product_ID', 'product name': 'product_name'}, inplace=True)

In [7]:
print(df)

     Unnamed: 0        ORDER ID           Unnamed: 2           Unnamed: 3  \
0             1  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
1             2  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
2             3  CA-2016-138688  2016-12-06 00:00:00            6/16/2016
3             4  US-2015-108966  2015-11-10 00:00:00           10/18/2015
4             5  US-2015-108966  2015-11-10 00:00:00           10/18/2015
..          ...             ...                  ...                  ...
149         150  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
150         151  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
151         152  CA-2016-158834            3/13/2016            3/16/2016
152         153  CA-2016-158834            3/13/2016            3/16/2016
153         154  CA-2015-124919            5/31/2015  2015-02-06 00:00:00

         Unnamed: 4 customer ID      customer name     segement  \
0      Second Class    CG-12520        Claire Gute     Consumer
1      Second Class    CG-12520        Claire Gute     Consumer
2      Second Class    DV-13045    Darrin Van Huff    Corporate
3    Standard Class    SO-20335     Sean O'Donnell     Consumer
4    Standard Class    SO-20335     Sean O'Donnell     Consumer
..              ...         ...                ...          ...
149  Standard Class    JE-16165     Justin Ellison    Corporate
150  Standard Class    JE-16165     Justin Ellison    Corporate
151     First Class    TW-21025  Tamara Willingham  Home Office
152     First Class    TW-21025  Tamara Willingham  Home Office
153     First Class    SP-20650   Stephanie Phelps    Corporate

           country             city  ... postal code    Rgion  \
0    United States        Henderson  ...       42420    South
1    United States        Henderson  ...       42420    South
2    United States      Los Angeles  ...       90036     West
3    United States  Fort Lauderdale  ...       33311    South
4    United States  Fort Lauderdale  ...       33311    South
..             ...              ...  ...         ...      ...
149  United States         Franklin  ...       53132  Central
150  United States         Franklin  ...       53132  Central
151  United States       Scottsdale  ...       85254     West
152  United States       Scottsdale  ...       85254     West
153  United States         San Jose  ...       95123     West

          product_ID         category sub-category  \
0    FUR-BO-10001798        Furniture    Bookcases
1    FUR-CH-10000454        Furniture       Chairs
2    OFF-LA-10000240  Office Supplies       Labels
3    FUR-TA-10000577        Furniture       Tables
4    OFF-ST-10000760  Office Supplies      Storage
..               ...              ...          ...
149  FUR-CH-10000454        Furniture       Chairs
150  OFF-BI-10002735  Office Supplies      Binders
151  OFF-AP-10000326  Office Supplies   Appliances
152  TEC-PH-10001254       Technology       Phones
153  OFF-PA-10001950  Office Supplies        Paper

                                          product_name      sales  \
0                    Bush Somerset Collection Bookcase   261.9600
1    Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400
2    Self-Adhesive Address Labels for Typewriters b...    14.6200
3        Bretford CR4500 Series Slim Rectangular Table   957.5775
4                       Eldon Fold 'N Roll Cart System    22.3680
..                                                 ...        ...
149  Hon Deluxe Fabric Upholstered Stacking Chairs,...  1951.8400
150                   GBC Prestige Therm-A-Bind Covers   171.5500
151  Belkin 7 Outlet SurgeMaster Surge Protector wi...   157.9200
152           Jabra BIZ 2300 Duo QD Duo CordedÂ Headset   203.1840
153  Southworth 25% Cotton Antique Laid Paper & Env...    58.3800

         Unnamed: 18 Unnamed: 19     #name
0    FUR-BO-10001798        0.00   41.9136
1    FUR-CH-10000454        0.00  219.5820
2    OFF-LA-10000240        0.00    6.8714
3    FUR-TA-10000577        0.45 -383.0310
4    OFF-ST-10000760        0.20    2.5164
..               ...         ...       ...
149  FUR-CH-10000454        0.00  585.5520
150  OFF-BI-10002735        0.00   80.6285
151  OFF-AP-10000326        0.20   17.7660
152  TEC-PH-10001254        0.20   15.2388
153  OFF-PA-10001950        0.00   26.2710

[154 rows x 21 columns]

In [43]:
print(df["sales"].sum())

31356.231699999997

In [45]:
print(df.describe)

<bound method NDFrame.describe of      Unnamed: 0        ORDER ID           Unnamed: 2           Unnamed: 3  \
0             1  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
1             2  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
2             3  CA-2016-138688  2016-12-06 00:00:00            6/16/2016
3             4  US-2015-108966  2015-11-10 00:00:00           10/18/2015
4             5  US-2015-108966  2015-11-10 00:00:00           10/18/2015
..          ...             ...                  ...                  ...
149         150  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
150         151  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
151         152  CA-2016-158834            3/13/2016            3/16/2016
152         153  CA-2016-158834            3/13/2016            3/16/2016
153         154  CA-2015-124919            5/31/2015  2015-02-06 00:00:00

         Unnamed: 4 customer ID      customer name     segement  \
0      Second Class    CG-12520        Claire Gute     Consumer
1      Second Class    CG-12520        Claire Gute     Consumer
2      Second Class    DV-13045    Darrin Van Huff    Corporate
3    Standard Class    SO-20335     Sean O'Donnell     Consumer
4    Standard Class    SO-20335     Sean O'Donnell     Consumer
..              ...         ...                ...          ...
149  Standard Class    JE-16165     Justin Ellison    Corporate
150  Standard Class    JE-16165     Justin Ellison    Corporate
151     First Class    TW-21025  Tamara Willingham  Home Office
152     First Class    TW-21025  Tamara Willingham  Home Office
153     First Class    SP-20650   Stephanie Phelps    Corporate

           country             city  ... postal code    Rgion  \
0    United States        Henderson  ...       42420    South
1    United States        Henderson  ...       42420    South
2    United States      Los Angeles  ...       90036     West
3    United States  Fort Lauderdale  ...       33311    South
4    United States  Fort Lauderdale  ...       33311    South
..             ...              ...  ...         ...      ...
149  United States         Franklin  ...       53132  Central
150  United States         Franklin  ...       53132  Central
151  United States       Scottsdale  ...       85254     West
152  United States       Scottsdale  ...       85254     West
153  United States         San Jose  ...       95123     West

          product_ID         category sub-category  \
0    FUR-BO-10001798        Furniture    Bookcases
1    FUR-CH-10000454        Furniture       Chairs
2    OFF-LA-10000240  Office Supplies       Labels
3    FUR-TA-10000577        Furniture       Tables
4    OFF-ST-10000760  Office Supplies      Storage
..               ...              ...          ...
149  FUR-CH-10000454        Furniture       Chairs
150  OFF-BI-10002735  Office Supplies      Binders
151  OFF-AP-10000326  Office Supplies   Appliances
152  TEC-PH-10001254       Technology       Phones
153  OFF-PA-10001950  Office Supplies        Paper

                                          product_name      sales  \
0                    Bush Somerset Collection Bookcase   261.9600
1    Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400
2    Self-Adhesive Address Labels for Typewriters b...    14.6200
3        Bretford CR4500 Series Slim Rectangular Table   957.5775
4                       Eldon Fold 'N Roll Cart System    22.3680
..                                                 ...        ...
149  Hon Deluxe Fabric Upholstered Stacking Chairs,...  1951.8400
150                   GBC Prestige Therm-A-Bind Covers   171.5500
151  Belkin 7 Outlet SurgeMaster Surge Protector wi...   157.9200
152           Jabra BIZ 2300 Duo QD Duo CordedÂ Headset   203.1840
153  Southworth 25% Cotton Antique Laid Paper & Env...    58.3800

         Unnamed: 18 Unnamed: 19     #name
0    FUR-BO-10001798        0.00   41.9136
1    FUR-CH-10000454        0.00  219.5820
2    OFF-LA-10000240        0.00    6.8714
3    FUR-TA-10000577        0.45 -383.0310
4    OFF-ST-10000760        0.20    2.5164
..               ...         ...       ...
149  FUR-CH-10000454        0.00  585.5520
150  OFF-BI-10002735        0.00   80.6285
151  OFF-AP-10000326        0.20   17.7660
152  TEC-PH-10001254        0.20   15.2388
153  OFF-PA-10001950        0.00   26.2710

[154 rows x 21 columns]>

In [47]:
print(df.items)

<bound method DataFrame.items of      Unnamed: 0        ORDER ID           Unnamed: 2           Unnamed: 3  \
0             1  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
1             2  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
2             3  CA-2016-138688  2016-12-06 00:00:00            6/16/2016
3             4  US-2015-108966  2015-11-10 00:00:00           10/18/2015
4             5  US-2015-108966  2015-11-10 00:00:00           10/18/2015
..          ...             ...                  ...                  ...
149         150  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
150         151  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
151         152  CA-2016-158834            3/13/2016            3/16/2016
152         153  CA-2016-158834            3/13/2016            3/16/2016
153         154  CA-2015-124919            5/31/2015  2015-02-06 00:00:00

         Unnamed: 4 customer ID      customer name     segement  \
0      Second Class    CG-12520        Claire Gute     Consumer
1      Second Class    CG-12520        Claire Gute     Consumer
2      Second Class    DV-13045    Darrin Van Huff    Corporate
3    Standard Class    SO-20335     Sean O'Donnell     Consumer
4    Standard Class    SO-20335     Sean O'Donnell     Consumer
..              ...         ...                ...          ...
149  Standard Class    JE-16165     Justin Ellison    Corporate
150  Standard Class    JE-16165     Justin Ellison    Corporate
151     First Class    TW-21025  Tamara Willingham  Home Office
152     First Class    TW-21025  Tamara Willingham  Home Office
153     First Class    SP-20650   Stephanie Phelps    Corporate

           country             city  ... postal code    Rgion  \
0    United States        Henderson  ...       42420    South
1    United States        Henderson  ...       42420    South
2    United States      Los Angeles  ...       90036     West
3    United States  Fort Lauderdale  ...       33311    South
4    United States  Fort Lauderdale  ...       33311    South
..             ...              ...  ...         ...      ...
149  United States         Franklin  ...       53132  Central
150  United States         Franklin  ...       53132  Central
151  United States       Scottsdale  ...       85254     West
152  United States       Scottsdale  ...       85254     West
153  United States         San Jose  ...       95123     West

          product_ID         category sub-category  \
0    FUR-BO-10001798        Furniture    Bookcases
1    FUR-CH-10000454        Furniture       Chairs
2    OFF-LA-10000240  Office Supplies       Labels
3    FUR-TA-10000577        Furniture       Tables
4    OFF-ST-10000760  Office Supplies      Storage
..               ...              ...          ...
149  FUR-CH-10000454        Furniture       Chairs
150  OFF-BI-10002735  Office Supplies      Binders
151  OFF-AP-10000326  Office Supplies   Appliances
152  TEC-PH-10001254       Technology       Phones
153  OFF-PA-10001950  Office Supplies        Paper

                                          product_name      sales  \
0                    Bush Somerset Collection Bookcase   261.9600
1    Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400
2    Self-Adhesive Address Labels for Typewriters b...    14.6200
3        Bretford CR4500 Series Slim Rectangular Table   957.5775
4                       Eldon Fold 'N Roll Cart System    22.3680
..                                                 ...        ...
149  Hon Deluxe Fabric Upholstered Stacking Chairs,...  1951.8400
150                   GBC Prestige Therm-A-Bind Covers   171.5500
151  Belkin 7 Outlet SurgeMaster Surge Protector wi...   157.9200
152           Jabra BIZ 2300 Duo QD Duo CordedÂ Headset   203.1840
153  Southworth 25% Cotton Antique Laid Paper & Env...    58.3800

         Unnamed: 18 Unnamed: 19     #name
0    FUR-BO-10001798        0.00   41.9136
1    FUR-CH-10000454        0.00  219.5820
2    OFF-LA-10000240        0.00    6.8714
3    FUR-TA-10000577        0.45 -383.0310
4    OFF-ST-10000760        0.20    2.5164
..               ...         ...       ...
149  FUR-CH-10000454        0.00  585.5520
150  OFF-BI-10002735        0.00   80.6285
151  OFF-AP-10000326        0.20   17.7660
152  TEC-PH-10001254        0.20   15.2388
153  OFF-PA-10001950        0.00   26.2710

[154 rows x 21 columns]>

In [9]:
df.isna()

,Unnamed: 0,ORDER ID,Unnamed: 2,Unnamed: 3,Unnamed: 4,customer ID,customer name,segement,country,city,...,postal code,Rgion,product ID,category,sub-category,product name,sales,Unnamed: 18,Unnamed: 19,#name
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
150,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
151,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
152,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
153,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
df.isna().sum()

Unnamed: 0       0
ORDER ID         0
Unnamed: 2       0
Unnamed: 3       0
Unnamed: 4       0
customer ID      0
customer name    0
segement         0
country          0
city             0
state            0
postal code      0
Rgion            0
product ID       0
category         0
sub-category     0
product name     0
sales            0
Unnamed: 18      0
Unnamed: 19      0
#name            0
dtype: int64

In [49]:
df1 = df.copy()
print(df1)

     Unnamed: 0        ORDER ID           Unnamed: 2           Unnamed: 3  \
0             1  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
1             2  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
2             3  CA-2016-138688  2016-12-06 00:00:00            6/16/2016
3             4  US-2015-108966  2015-11-10 00:00:00           10/18/2015
4             5  US-2015-108966  2015-11-10 00:00:00           10/18/2015
..          ...             ...                  ...                  ...
149         150  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
150         151  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
151         152  CA-2016-158834            3/13/2016            3/16/2016
152         153  CA-2016-158834            3/13/2016            3/16/2016
153         154  CA-2015-124919            5/31/2015  2015-02-06 00:00:00

         Unnamed: 4 customer ID      customer name     segement  \
0      Second Class    CG-12520        Claire Gute     Consumer
1      Second Class    CG-12520        Claire Gute     Consumer
2      Second Class    DV-13045    Darrin Van Huff    Corporate
3    Standard Class    SO-20335     Sean O'Donnell     Consumer
4    Standard Class    SO-20335     Sean O'Donnell     Consumer
..              ...         ...                ...          ...
149  Standard Class    JE-16165     Justin Ellison    Corporate
150  Standard Class    JE-16165     Justin Ellison    Corporate
151     First Class    TW-21025  Tamara Willingham  Home Office
152     First Class    TW-21025  Tamara Willingham  Home Office
153     First Class    SP-20650   Stephanie Phelps    Corporate

           country             city  ... postal code    Rgion  \
0    United States        Henderson  ...       42420    South
1    United States        Henderson  ...       42420    South
2    United States      Los Angeles  ...       90036     West
3    United States  Fort Lauderdale  ...       33311    South
4    United States  Fort Lauderdale  ...       33311    South
..             ...              ...  ...         ...      ...
149  United States         Franklin  ...       53132  Central
150  United States         Franklin  ...       53132  Central
151  United States       Scottsdale  ...       85254     West
152  United States       Scottsdale  ...       85254     West
153  United States         San Jose  ...       95123     West

          product_ID         category sub-category  \
0    FUR-BO-10001798        Furniture    Bookcases
1    FUR-CH-10000454        Furniture       Chairs
2    OFF-LA-10000240  Office Supplies       Labels
3    FUR-TA-10000577        Furniture       Tables
4    OFF-ST-10000760  Office Supplies      Storage
..               ...              ...          ...
149  FUR-CH-10000454        Furniture       Chairs
150  OFF-BI-10002735  Office Supplies      Binders
151  OFF-AP-10000326  Office Supplies   Appliances
152  TEC-PH-10001254       Technology       Phones
153  OFF-PA-10001950  Office Supplies        Paper

                                          product_name      sales  \
0                    Bush Somerset Collection Bookcase   261.9600
1    Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400
2    Self-Adhesive Address Labels for Typewriters b...    14.6200
3        Bretford CR4500 Series Slim Rectangular Table   957.5775
4                       Eldon Fold 'N Roll Cart System    22.3680
..                                                 ...        ...
149  Hon Deluxe Fabric Upholstered Stacking Chairs,...  1951.8400
150                   GBC Prestige Therm-A-Bind Covers   171.5500
151  Belkin 7 Outlet SurgeMaster Surge Protector wi...   157.9200
152           Jabra BIZ 2300 Duo QD Duo CordedÂ Headset   203.1840
153  Southworth 25% Cotton Antique Laid Paper & Env...    58.3800

         Unnamed: 18 Unnamed: 19     #name
0    FUR-BO-10001798        0.00   41.9136
1    FUR-CH-10000454        0.00  219.5820
2    OFF-LA-10000240        0.00    6.8714
3    FUR-TA-10000577        0.45 -383.0310
4    OFF-ST-10000760        0.20    2.5164
..               ...         ...       ...
149  FUR-CH-10000454        0.00  585.5520
150  OFF-BI-10002735        0.00   80.6285
151  OFF-AP-10000326        0.20   17.7660
152  TEC-PH-10001254        0.20   15.2388
153  OFF-PA-10001950        0.00   26.2710

[154 rows x 21 columns]

In [51]:
print(df1)

     Unnamed: 0        ORDER ID           Unnamed: 2           Unnamed: 3  \
0             1  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
1             2  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
2             3  CA-2016-138688  2016-12-06 00:00:00            6/16/2016
3             4  US-2015-108966  2015-11-10 00:00:00           10/18/2015
4             5  US-2015-108966  2015-11-10 00:00:00           10/18/2015
..          ...             ...                  ...                  ...
149         150  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
150         151  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
151         152  CA-2016-158834            3/13/2016            3/16/2016
152         153  CA-2016-158834            3/13/2016            3/16/2016
153         154  CA-2015-124919            5/31/2015  2015-02-06 00:00:00

         Unnamed: 4 customer ID      customer name     segement  \
0      Second Class    CG-12520        Claire Gute     Consumer
1      Second Class    CG-12520        Claire Gute     Consumer
2      Second Class    DV-13045    Darrin Van Huff    Corporate
3    Standard Class    SO-20335     Sean O'Donnell     Consumer
4    Standard Class    SO-20335     Sean O'Donnell     Consumer
..              ...         ...                ...          ...
149  Standard Class    JE-16165     Justin Ellison    Corporate
150  Standard Class    JE-16165     Justin Ellison    Corporate
151     First Class    TW-21025  Tamara Willingham  Home Office
152     First Class    TW-21025  Tamara Willingham  Home Office
153     First Class    SP-20650   Stephanie Phelps    Corporate

           country             city  ... postal code    Rgion  \
0    United States        Henderson  ...       42420    South
1    United States        Henderson  ...       42420    South
2    United States      Los Angeles  ...       90036     West
3    United States  Fort Lauderdale  ...       33311    South
4    United States  Fort Lauderdale  ...       33311    South
..             ...              ...  ...         ...      ...
149  United States         Franklin  ...       53132  Central
150  United States         Franklin  ...       53132  Central
151  United States       Scottsdale  ...       85254     West
152  United States       Scottsdale  ...       85254     West
153  United States         San Jose  ...       95123     West

          product_ID         category sub-category  \
0    FUR-BO-10001798        Furniture    Bookcases
1    FUR-CH-10000454        Furniture       Chairs
2    OFF-LA-10000240  Office Supplies       Labels
3    FUR-TA-10000577        Furniture       Tables
4    OFF-ST-10000760  Office Supplies      Storage
..               ...              ...          ...
149  FUR-CH-10000454        Furniture       Chairs
150  OFF-BI-10002735  Office Supplies      Binders
151  OFF-AP-10000326  Office Supplies   Appliances
152  TEC-PH-10001254       Technology       Phones
153  OFF-PA-10001950  Office Supplies        Paper

                                          product_name      sales  \
0                    Bush Somerset Collection Bookcase   261.9600
1    Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400
2    Self-Adhesive Address Labels for Typewriters b...    14.6200
3        Bretford CR4500 Series Slim Rectangular Table   957.5775
4                       Eldon Fold 'N Roll Cart System    22.3680
..                                                 ...        ...
149  Hon Deluxe Fabric Upholstered Stacking Chairs,...  1951.8400
150                   GBC Prestige Therm-A-Bind Covers   171.5500
151  Belkin 7 Outlet SurgeMaster Surge Protector wi...   157.9200
152           Jabra BIZ 2300 Duo QD Duo CordedÂ Headset   203.1840
153  Southworth 25% Cotton Antique Laid Paper & Env...    58.3800

         Unnamed: 18 Unnamed: 19     #name
0    FUR-BO-10001798        0.00   41.9136
1    FUR-CH-10000454        0.00  219.5820
2    OFF-LA-10000240        0.00    6.8714
3    FUR-TA-10000577        0.45 -383.0310
4    OFF-ST-10000760        0.20    2.5164
..               ...         ...       ...
149  FUR-CH-10000454        0.00  585.5520
150  OFF-BI-10002735        0.00   80.6285
151  OFF-AP-10000326        0.20   17.7660
152  TEC-PH-10001254        0.20   15.2388
153  OFF-PA-10001950        0.00   26.2710

[154 rows x 21 columns]

In [53]:
df1.drop(['country','city'],axis =1,inplace=True)

In [55]:
print(df1)

     Unnamed: 0        ORDER ID           Unnamed: 2           Unnamed: 3  \
0             1  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
1             2  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
2             3  CA-2016-138688  2016-12-06 00:00:00            6/16/2016
3             4  US-2015-108966  2015-11-10 00:00:00           10/18/2015
4             5  US-2015-108966  2015-11-10 00:00:00           10/18/2015
..          ...             ...                  ...                  ...
149         150  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
150         151  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
151         152  CA-2016-158834            3/13/2016            3/16/2016
152         153  CA-2016-158834            3/13/2016            3/16/2016
153         154  CA-2015-124919            5/31/2015  2015-02-06 00:00:00

         Unnamed: 4 customer ID      customer name     segement       state  \
0      Second Class    CG-12520        Claire Gute     Consumer    Kentucky
1      Second Class    CG-12520        Claire Gute     Consumer    Kentucky
2      Second Class    DV-13045    Darrin Van Huff    Corporate  California
3    Standard Class    SO-20335     Sean O'Donnell     Consumer     Florida
4    Standard Class    SO-20335     Sean O'Donnell     Consumer     Florida
..              ...         ...                ...          ...         ...
149  Standard Class    JE-16165     Justin Ellison    Corporate   Wisconsin
150  Standard Class    JE-16165     Justin Ellison    Corporate   Wisconsin
151     First Class    TW-21025  Tamara Willingham  Home Office     Arizona
152     First Class    TW-21025  Tamara Willingham  Home Office     Arizona
153     First Class    SP-20650   Stephanie Phelps    Corporate  California

     postal code    Rgion       product_ID         category sub-category  \
0          42420    South  FUR-BO-10001798        Furniture    Bookcases
1          42420    South  FUR-CH-10000454        Furniture       Chairs
2          90036     West  OFF-LA-10000240  Office Supplies       Labels
3          33311    South  FUR-TA-10000577        Furniture       Tables
4          33311    South  OFF-ST-10000760  Office Supplies      Storage
..           ...      ...              ...              ...          ...
149        53132  Central  FUR-CH-10000454        Furniture       Chairs
150        53132  Central  OFF-BI-10002735  Office Supplies      Binders
151        85254     West  OFF-AP-10000326  Office Supplies   Appliances
152        85254     West  TEC-PH-10001254       Technology       Phones
153        95123     West  OFF-PA-10001950  Office Supplies        Paper

                                          product_name      sales  \
0                    Bush Somerset Collection Bookcase   261.9600
1    Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400
2    Self-Adhesive Address Labels for Typewriters b...    14.6200
3        Bretford CR4500 Series Slim Rectangular Table   957.5775
4                       Eldon Fold 'N Roll Cart System    22.3680
..                                                 ...        ...
149  Hon Deluxe Fabric Upholstered Stacking Chairs,...  1951.8400
150                   GBC Prestige Therm-A-Bind Covers   171.5500
151  Belkin 7 Outlet SurgeMaster Surge Protector wi...   157.9200
152           Jabra BIZ 2300 Duo QD Duo CordedÂ Headset   203.1840
153  Southworth 25% Cotton Antique Laid Paper & Env...    58.3800

         Unnamed: 18  Unnamed: 19     #name
0    FUR-BO-10001798         0.00   41.9136
1    FUR-CH-10000454         0.00  219.5820
2    OFF-LA-10000240         0.00    6.8714
3    FUR-TA-10000577         0.45 -383.0310
4    OFF-ST-10000760         0.20    2.5164
..               ...          ...       ...
149  FUR-CH-10000454         0.00  585.5520
150  OFF-BI-10002735         0.00   80.6285
151  OFF-AP-10000326         0.20   17.7660
152  TEC-PH-10001254         0.20   15.2388
153  OFF-PA-10001950         0.00   26.2710

[154 rows x 19 columns]

In [31]:
print(df)

     Unnamed: 0        ORDER ID           Unnamed: 2           Unnamed: 3  \
0             1  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
1             2  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
2             3  CA-2016-138688  2016-12-06 00:00:00            6/16/2016
3             4  US-2015-108966  2015-11-10 00:00:00           10/18/2015
4             5  US-2015-108966  2015-11-10 00:00:00           10/18/2015
..          ...             ...                  ...                  ...
149         150  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
150         151  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
151         152  CA-2016-158834            3/13/2016            3/16/2016
152         153  CA-2016-158834            3/13/2016            3/16/2016
153         154  CA-2015-124919            5/31/2015  2015-02-06 00:00:00

         Unnamed: 4 customer ID      customer name     segement       state  \
0      Second Class    CG-12520        Claire Gute     Consumer    Kentucky
1      Second Class    CG-12520        Claire Gute     Consumer    Kentucky
2      Second Class    DV-13045    Darrin Van Huff    Corporate  California
3    Standard Class    SO-20335     Sean O'Donnell     Consumer     Florida
4    Standard Class    SO-20335     Sean O'Donnell     Consumer     Florida
..              ...         ...                ...          ...         ...
149  Standard Class    JE-16165     Justin Ellison    Corporate   Wisconsin
150  Standard Class    JE-16165     Justin Ellison    Corporate   Wisconsin
151     First Class    TW-21025  Tamara Willingham  Home Office     Arizona
152     First Class    TW-21025  Tamara Willingham  Home Office     Arizona
153     First Class    SP-20650   Stephanie Phelps    Corporate  California

     postal code    Rgion       product ID         category sub-category  \
0          42420    South  FUR-BO-10001798        Furniture    Bookcases
1          42420    South  FUR-CH-10000454        Furniture       Chairs
2          90036     West  OFF-LA-10000240  Office Supplies       Labels
3          33311    South  FUR-TA-10000577        Furniture       Tables
4          33311    South  OFF-ST-10000760  Office Supplies      Storage
..           ...      ...              ...              ...          ...
149        53132  Central  FUR-CH-10000454        Furniture       Chairs
150        53132  Central  OFF-BI-10002735  Office Supplies      Binders
151        85254     West  OFF-AP-10000326  Office Supplies   Appliances
152        85254     West  TEC-PH-10001254       Technology       Phones
153        95123     West  OFF-PA-10001950  Office Supplies        Paper

                                          product name      sales  \
0                    Bush Somerset Collection Bookcase   261.9600
1    Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400
2    Self-Adhesive Address Labels for Typewriters b...    14.6200
3        Bretford CR4500 Series Slim Rectangular Table   957.5775
4                       Eldon Fold 'N Roll Cart System    22.3680
..                                                 ...        ...
149  Hon Deluxe Fabric Upholstered Stacking Chairs,...  1951.8400
150                   GBC Prestige Therm-A-Bind Covers   171.5500
151  Belkin 7 Outlet SurgeMaster Surge Protector wi...   157.9200
152           Jabra BIZ 2300 Duo QD Duo CordedÂ Headset   203.1840
153  Southworth 25% Cotton Antique Laid Paper & Env...    58.3800

         Unnamed: 18  Unnamed: 19     #name
0    FUR-BO-10001798         0.00   41.9136
1    FUR-CH-10000454         0.00  219.5820
2    OFF-LA-10000240         0.00    6.8714
3    FUR-TA-10000577         0.45 -383.0310
4    OFF-ST-10000760         0.20    2.5164
..               ...          ...       ...
149  FUR-CH-10000454         0.00  585.5520
150  OFF-BI-10002735         0.00   80.6285
151  OFF-AP-10000326         0.20   17.7660
152  TEC-PH-10001254         0.20   15.2388
153  OFF-PA-10001950         0.00   26.2710

[154 rows x 19 columns]

In [57]:
print(df)

     Unnamed: 0        ORDER ID           Unnamed: 2           Unnamed: 3  \
0             1  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
1             2  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
2             3  CA-2016-138688  2016-12-06 00:00:00            6/16/2016
3             4  US-2015-108966  2015-11-10 00:00:00           10/18/2015
4             5  US-2015-108966  2015-11-10 00:00:00           10/18/2015
..          ...             ...                  ...                  ...
149         150  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
150         151  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
151         152  CA-2016-158834            3/13/2016            3/16/2016
152         153  CA-2016-158834            3/13/2016            3/16/2016
153         154  CA-2015-124919            5/31/2015  2015-02-06 00:00:00

         Unnamed: 4 customer ID      customer name     segement  \
0      Second Class    CG-12520        Claire Gute     Consumer
1      Second Class    CG-12520        Claire Gute     Consumer
2      Second Class    DV-13045    Darrin Van Huff    Corporate
3    Standard Class    SO-20335     Sean O'Donnell     Consumer
4    Standard Class    SO-20335     Sean O'Donnell     Consumer
..              ...         ...                ...          ...
149  Standard Class    JE-16165     Justin Ellison    Corporate
150  Standard Class    JE-16165     Justin Ellison    Corporate
151     First Class    TW-21025  Tamara Willingham  Home Office
152     First Class    TW-21025  Tamara Willingham  Home Office
153     First Class    SP-20650   Stephanie Phelps    Corporate

           country             city  ... postal code    Rgion  \
0    United States        Henderson  ...       42420    South
1    United States        Henderson  ...       42420    South
2    United States      Los Angeles  ...       90036     West
3    United States  Fort Lauderdale  ...       33311    South
4    United States  Fort Lauderdale  ...       33311    South
..             ...              ...  ...         ...      ...
149  United States         Franklin  ...       53132  Central
150  United States         Franklin  ...       53132  Central
151  United States       Scottsdale  ...       85254     West
152  United States       Scottsdale  ...       85254     West
153  United States         San Jose  ...       95123     West

          product_ID         category sub-category  \
0    FUR-BO-10001798        Furniture    Bookcases
1    FUR-CH-10000454        Furniture       Chairs
2    OFF-LA-10000240  Office Supplies       Labels
3    FUR-TA-10000577        Furniture       Tables
4    OFF-ST-10000760  Office Supplies      Storage
..               ...              ...          ...
149  FUR-CH-10000454        Furniture       Chairs
150  OFF-BI-10002735  Office Supplies      Binders
151  OFF-AP-10000326  Office Supplies   Appliances
152  TEC-PH-10001254       Technology       Phones
153  OFF-PA-10001950  Office Supplies        Paper

                                          product_name      sales  \
0                    Bush Somerset Collection Bookcase   261.9600
1    Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400
2    Self-Adhesive Address Labels for Typewriters b...    14.6200
3        Bretford CR4500 Series Slim Rectangular Table   957.5775
4                       Eldon Fold 'N Roll Cart System    22.3680
..                                                 ...        ...
149  Hon Deluxe Fabric Upholstered Stacking Chairs,...  1951.8400
150                   GBC Prestige Therm-A-Bind Covers   171.5500
151  Belkin 7 Outlet SurgeMaster Surge Protector wi...   157.9200
152           Jabra BIZ 2300 Duo QD Duo CordedÂ Headset   203.1840
153  Southworth 25% Cotton Antique Laid Paper & Env...    58.3800

         Unnamed: 18 Unnamed: 19     #name
0    FUR-BO-10001798        0.00   41.9136
1    FUR-CH-10000454        0.00  219.5820
2    OFF-LA-10000240        0.00    6.8714
3    FUR-TA-10000577        0.45 -383.0310
4    OFF-ST-10000760        0.20    2.5164
..               ...         ...       ...
149  FUR-CH-10000454        0.00  585.5520
150  OFF-BI-10002735        0.00   80.6285
151  OFF-AP-10000326        0.20   17.7660
152  TEC-PH-10001254        0.20   15.2388
153  OFF-PA-10001950        0.00   26.2710

[154 rows x 21 columns]

In [59]:
print(df1)

     Unnamed: 0        ORDER ID           Unnamed: 2           Unnamed: 3  \
0             1  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
1             2  CA-2016-152156  2016-08-11 00:00:00  2016-11-11 00:00:00
2             3  CA-2016-138688  2016-12-06 00:00:00            6/16/2016
3             4  US-2015-108966  2015-11-10 00:00:00           10/18/2015
4             5  US-2015-108966  2015-11-10 00:00:00           10/18/2015
..          ...             ...                  ...                  ...
149         150  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
150         151  CA-2016-114489  2016-05-12 00:00:00  2016-09-12 00:00:00
151         152  CA-2016-158834            3/13/2016            3/16/2016
152         153  CA-2016-158834            3/13/2016            3/16/2016
153         154  CA-2015-124919            5/31/2015  2015-02-06 00:00:00

         Unnamed: 4 customer ID      customer name     segement       state  \
0      Second Class    CG-12520        Claire Gute     Consumer    Kentucky
1      Second Class    CG-12520        Claire Gute     Consumer    Kentucky
2      Second Class    DV-13045    Darrin Van Huff    Corporate  California
3    Standard Class    SO-20335     Sean O'Donnell     Consumer     Florida
4    Standard Class    SO-20335     Sean O'Donnell     Consumer     Florida
..              ...         ...                ...          ...         ...
149  Standard Class    JE-16165     Justin Ellison    Corporate   Wisconsin
150  Standard Class    JE-16165     Justin Ellison    Corporate   Wisconsin
151     First Class    TW-21025  Tamara Willingham  Home Office     Arizona
152     First Class    TW-21025  Tamara Willingham  Home Office     Arizona
153     First Class    SP-20650   Stephanie Phelps    Corporate  California

     postal code    Rgion       product_ID         category sub-category  \
0          42420    South  FUR-BO-10001798        Furniture    Bookcases
1          42420    South  FUR-CH-10000454        Furniture       Chairs
2          90036     West  OFF-LA-10000240  Office Supplies       Labels
3          33311    South  FUR-TA-10000577        Furniture       Tables
4          33311    South  OFF-ST-10000760  Office Supplies      Storage
..           ...      ...              ...              ...          ...
149        53132  Central  FUR-CH-10000454        Furniture       Chairs
150        53132  Central  OFF-BI-10002735  Office Supplies      Binders
151        85254     West  OFF-AP-10000326  Office Supplies   Appliances
152        85254     West  TEC-PH-10001254       Technology       Phones
153        95123     West  OFF-PA-10001950  Office Supplies        Paper

                                          product_name      sales  \
0                    Bush Somerset Collection Bookcase   261.9600
1    Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400
2    Self-Adhesive Address Labels for Typewriters b...    14.6200
3        Bretford CR4500 Series Slim Rectangular Table   957.5775
4                       Eldon Fold 'N Roll Cart System    22.3680
..                                                 ...        ...
149  Hon Deluxe Fabric Upholstered Stacking Chairs,...  1951.8400
150                   GBC Prestige Therm-A-Bind Covers   171.5500
151  Belkin 7 Outlet SurgeMaster Surge Protector wi...   157.9200
152           Jabra BIZ 2300 Duo QD Duo CordedÂ Headset   203.1840
153  Southworth 25% Cotton Antique Laid Paper & Env...    58.3800

         Unnamed: 18  Unnamed: 19     #name
0    FUR-BO-10001798         0.00   41.9136
1    FUR-CH-10000454         0.00  219.5820
2    OFF-LA-10000240         0.00    6.8714
3    FUR-TA-10000577         0.45 -383.0310
4    OFF-ST-10000760         0.20    2.5164
..               ...          ...       ...
149  FUR-CH-10000454         0.00  585.5520
150  OFF-BI-10002735         0.00   80.6285
151  OFF-AP-10000326         0.20   17.7660
152  TEC-PH-10001254         0.20   15.2388
153  OFF-PA-10001950         0.00   26.2710

[154 rows x 19 columns]